# Generated by Django 5.2.12 on 2026-05-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "博客", "verbose_name_plural": "博客"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "评论", "verbose_name_plural": "评论"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="pub_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="Home.blog",
                verbose_name="评论",
            ),
        ),
    ]
