# Generated by Django 5.2.12 on 2026-05-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_alter_blog_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
