# Generated by Django 5.2.12 on 2026-05-25 16:39

import Buser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png", upload_to=Buser.models.rename_avatar
            ),
        ),
    ]
